(() => {
  const U = localStorage.getItem('weatherUnit') || 'metric';
  const state = { unit: U, places: JSON.parse(localStorage.getItem('savedPlaces') || '[]'), request: null, current: null };
  const esc = value => String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const icon = id => `https://openweathermap.org/img/wn/${id}@2x.png`;
  const unit = () => state.unit === 'metric' ? '°C' : '°F';
  const $ = id => document.getElementById(id);
  document.body.innerHTML = `<main class="atmos"><header class="atmos-top"><div class="atmos-brand"><b>✦</b> Atmos</div><div class="atmos-tools"><button class="tool" id="units" aria-label="Switch temperature units">${unit()}</button><button class="tool" id="theme" aria-label="Toggle theme">◐</button></div></header><form class="search" id="form"><input id="query" autocomplete="off" placeholder="Search a city or place" aria-label="City or place"><button class="search-submit">Search</button><button class="loc" id="location" type="button" title="Use my location" aria-label="Use my location">⌖</button><div id="suggestions" class="suggestions" hidden></div></form><p id="status" class="status" aria-live="polite">Search for a place to see the forecast.</p><section id="saved" class="saved" aria-label="Saved locations"></section><section id="content" hidden><article id="hero" class="current"></article><section class="section"><div class="section-head"><h2>Next 24 hours</h2><span id="updated"></span></div><div id="hours" class="hours"></div></section><section class="section"><div class="section-head"><h2>5-day outlook</h2><span>High / low</span></div><div id="daily" class="daily"></div></section><section class="section details"><h2>Weather details</h2><div id="details" class="detail-grid"></div></section></section></main>`;
  const date = (stamp, offset, opts) => new Intl.DateTimeFormat(undefined, {timeZone:'UTC', ...opts}).format(new Date((stamp + offset) * 1000));
  const setStatus = (message, bad = false) => { $('status').textContent = message; $('status').className = `status${bad ? ' error' : ''}`; };
  const wind = deg => ['N','NE','E','SE','S','SW','W','NW'][Math.round((deg || 0) / 45) % 8];
  const fetchJSON = async (path, signal) => { const response = await fetch(path,{signal}); const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Weather data is unavailable.'); return data; };
  const cardClass = weather => { const m = weather.main.toLowerCase(); return `${weather.icon.endsWith('n') ? 'night ' : ''}${m.includes('thunder')?'thunder':m.includes('rain')||m.includes('drizzle')?'rain':m.includes('snow')?'snow':m.includes('cloud')?'clouds':''}`; };
  function showCurrent(data) { const weather=data.weather[0], speed=state.unit==='metric'?'m/s':'mph'; $('hero').className=`current ${cardClass(weather)}`; $('hero').innerHTML=`<p class="place">${esc(data.name)}, ${esc(data.sys.country)}</p><p class="condition">${esc(weather.description)}</p><p class="temp">${Math.round(data.main.temp)}<span>${unit()}</span></p><p class="feels">Feels like ${Math.round(data.main.feels_like)}${unit()}</p><img class="hero-icon" src="${icon(weather.icon)}" alt="${esc(weather.description)}">`; $('updated').textContent=`Updated ${date(data.dt,data.timezone,{hour:'numeric',minute:'2-digit'})}`; const details=[['Feels like',`${Math.round(data.main.feels_like)}${unit()}`],['Humidity',`${data.main.humidity}%`],['Wind',`${Math.round(data.wind.speed)} ${speed} ${wind(data.wind.deg)}`],['Pressure',`${data.main.pressure} hPa`],['Visibility',data.visibility?`${(data.visibility/1000).toFixed(1)} km`:'—'],['Sunrise',date(data.sys.sunrise,data.timezone,{hour:'numeric',minute:'2-digit'})],['Sunset',date(data.sys.sunset,data.timezone,{hour:'numeric',minute:'2-digit'})]]; $('details').innerHTML=details.map(d=>`<div class="detail"><span>${d[0]}</span><strong>${d[1]}</strong></div>`).join(''); }
  function showForecast(data, offset) { $('hours').innerHTML=data.list.slice(0,8).map((x,i)=>`<article class="hour"><time>${i?' '+date(x.dt,offset,{hour:'numeric'}):'Now'}</time><img src="${icon(x.weather[0].icon)}" alt="${esc(x.weather[0].description)}"><strong>${Math.round(x.main.temp)}${unit()}</strong></article>`).join(''); const groups=new Map(); data.list.forEach(x=>{const key=date(x.dt,offset,{year:'numeric',month:'2-digit',day:'2-digit'});groups.set(key,[...(groups.get(key)||[]),x])}); const first=[...groups.keys()][0]; $('daily').innerHTML=[...groups].slice(0,5).map(([key,items])=>{const representative=items[Math.min(3,items.length-1)], hi=Math.max(...items.map(x=>x.main.temp_max)),lo=Math.min(...items.map(x=>x.main.temp_min)),pop=Math.round(Math.max(...items.map(x=>x.pop||0))*100),label=key===first?'Today':date(items[0].dt,offset,{weekday:'long'}),w=representative.weather[0];return `<article><div><strong>${label}</strong><small>${esc(w.description)}</small></div><img src="${icon(w.icon)}" alt="${esc(w.description)}"><div class="temps">${Math.round(hi)}° <span>${Math.round(lo)}°</span></div><div class="pop">${pop?`☂ ${pop}%`:''}</div></article>`}).join(''); }
  function renderSaved() { $('saved').innerHTML=state.places.map((p,i)=>`<button data-place="${i}">${esc(p.label)}</button>`).join(''); [...$('saved').querySelectorAll('button')].forEach(b=>b.onclick=()=>{const p=state.places[b.dataset.place];$('query').value=p.label;load(p.params,p.label)}); }
  function savePlace(place) { state.places=[place,...state.places.filter(x=>JSON.stringify(x.params)!==JSON.stringify(place.params))].slice(0,5);localStorage.setItem('savedPlaces',JSON.stringify(state.places));renderSaved(); }
  async function load(params,label) { state.request?.abort(); state.request=new AbortController(); $('suggestions').hidden=true;$('content').hidden=true;setStatus('Fetching the latest weather…'); const search=new URLSearchParams({...params,units:state.unit}); try { const [current,forecast]=await Promise.all([fetchJSON(`/api/weather?${search}`,state.request.signal),fetchJSON(`/api/forecast?${search}`,state.request.signal)]);state.current={params,label};showCurrent(current);showForecast(forecast,forecast.city.timezone);$('content').hidden=false;setStatus(`Weather for ${current.name}.`);savePlace({label:current.name,params});} catch(error) {if(error.name!=='AbortError')setStatus(error.message,true)} }
  let timer; async function suggest() { const q=$('query').value.trim(),box=$('suggestions');if(q.length<2){box.hidden=true;return}try{const places=await fetchJSON(`/api/geocode?q=${encodeURIComponent(q)}&limit=5`);box.innerHTML=places.map((p,i)=>`<button type="button" class="suggestion" data-index="${i}">${esc(p.name)} <small>${esc([p.state,p.country].filter(Boolean).join(', '))}</small></button>`).join('');box.hidden=!places.length;[...box.querySelectorAll('button')].forEach(b=>b.onclick=()=>{const p=places[b.dataset.index];$('query').value=`${p.name}, ${p.country}`;load({lat:p.lat,lon:p.lon},p.name)})}catch{box.hidden=true}}
  $('form').onsubmit=e=>{e.preventDefault();const q=$('query').value.trim();q?load({city:q},q):setStatus('Enter a city or choose a suggestion.',true)};$('query').oninput=()=>{clearTimeout(timer);timer=setTimeout(suggest,300)};$('location').onclick=()=>{if(!navigator.geolocation)return setStatus('Location search is not supported.',true);setStatus('Requesting your location…');navigator.geolocation.getCurrentPosition(p=>load({lat:p.coords.latitude,lon:p.coords.longitude},'Current location'),()=>setStatus('Location unavailable. Search for a city instead.',true),{enableHighAccuracy:false,timeout:10000,maximumAge:300000})};$('units').onclick=()=>{state.unit=state.unit==='metric'?'imperial':'metric';localStorage.setItem('weatherUnit',state.unit);$('units').textContent=unit();if(state.current)load(state.current.params,state.current.label)};$('theme').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('theme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('theme')==='dark')document.body.classList.add('dark');renderSaved();
})();
